### PR TITLE
Fixes float search + add option to search by type

### LINKED ISSUE #23: Float Search Doesn't Work
I have tried in multiple games to search for floats.

When float32 is selected, no search is performed at all and the number of matches is blank instead of 0.
When float64 is selected, it seems like no search is performed, but the matches found text gets a random new line in it and the matches returned can't be seen.

### PR DESCRIPTION
**Pull request by cescofry**
Following @kayon suggestion [here](https://github.com/CameronRedmore/memory-deck/issues/8#issuecomment-1423817497) I fixed the float search and I added a new command to set a specific search_type.

Fixes: https://github.com/CameronRedmore/memory-deck/issues/23

### CODE REVIEW

**Comment by HeyItsWaters** [comment]
@cescofry let me know when this is ready to get pushed to the main Decky store and I can get that started.

**Comment by cescofry** [comment]
I think it is ready. I have to admit that I don't have much knowledge of cheat engines, so I assume how thinks work more than actually know. But in this case, every float search was automatically returning an error as the memscanner was not set for floats, so it should not cause a regression.

**Comment by HeyItsWaters** [comment]
@cescofry  to get this into the Decky store we have to bump the version number and submit a Pull Request against the decky-plugin-database repo hosted by the Steam Deck Homebrew folks.

i'm happy to do so, just need to know this change was thoroughly tested first.

**Comment by cescofry** [comment]
Following the comment above. This has not been thoroughly tested. Mostly because I don't know how to test this project properly, I am new to this space and there is not a test script for the project itself. 
I am on vacation for a few days, but I can maybe have a crack at testing more once I am back. 
Could you please provide a quick list of tests that I could perform? That, I think, could also help other people contributions. 
Even better would be setting up some basic unit tests (or maybe integration tests against a dummy binary process) but I understand that may be overcomplicated.

**Comment by HeyItsWaters** [comment]
@cescofry all good points.

If we could set up unit tests that would awesome.

Usually when a new version of a plugin is submitted to the store, they ask that you've tested against every combination of SteamOS stable/beta and Decky stable/pre-release.

In the past, I just copy the changes to my SteamDeck manually using the build in .vscode automations.

**Comment by cescofry** [comment]
In that sense I did test it on my deck (steamOS 3.4.6), running Hades, which stores all the items in floats.

**Comment by HeyItsWaters** [comment]
@cescofry that's good enough for me. If I get some time tonight I'll push your changes to my SD and test as well, then submit the required stuff to the SDH decky repo so this gets rolled out.

**Comment by cescofry** [comment]
I guess our changes will go in the stating build of decky. We could ask support on discord for some additional testing.

**Comment by HeyItsWaters** [comment]
@cescofry  I have submitted PR https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/345

Once this is initially approved, it should get deployed to the Decky "testing" store. Once we validate it there, we can ask the folks in the #plugin-dev channel to push it to production.

**Comment by HeyItsWaters** [comment]
fyi - i bumped the plugin version in the plugin.json file so that the changes actually get pulled in.

For any future PRs you submit, please do this as well. Thanks for the help with this!

**Pull request merged**
